import json
import logging
import os
from contextlib import asynccontextmanager
from typing import Any, Dict, List

# Third-party imports for web server and data validation
from fastapi import FastAPI, HTTPException

# Google ADK imports
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.events import Event, EventActions
from google.adk.models import EventInput, Model
from google.adk.runners import InvocationContext, Runner
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field

# --- 1. Configuration and Setup ---

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("OpsSage")

# IMPORTANT: You must configure your environment variables for the ADK/Gemini model
# GOOGLE_API_KEY or GOOGLE_GENAI_USE_VERTEXAI must be set in the environment where this runs.
MODEL_NAME = "gemini-2.5-flash"
DB_PATH = "opssage_knowledge.json"  # Placeholder for local RAG indexing file

# --- 2. Pydantic Models for API and Agent Output ---


class AlertData(BaseModel):
    """A simplified model for a single alert from Alertmanager."""

    startsAt: str = Field(..., description="Timestamp of when the alert started.")
    status: str = Field(..., description="Current status (e.g., 'firing', 'resolved').")
    labels: Dict[str, str] = Field(
        ...,
        description="Key-value pairs identifying the alert source (e.g., 'alertname', 'instance').",
    )
    annotations: Dict[str, str] = Field(
        ...,
        description="Key-value pairs with descriptive information (e.g., 'summary', 'description').",
    )


class AlertPayload(BaseModel):
    """The full payload structure expected from Alertmanager."""

    version: str
    status: str
    alerts: List[AlertData]
    receiver: str
    groupKey: str


class AnalysisReport(BaseModel):
    """Structured output from the OpsSage system."""

    alert_name: str = Field(..., description="The primary name of the alert.")
    severity: str = Field(
        ...,
        description="The determined severity (e.g., 'Critical', 'Warning', 'Info').",
    )
    analysis_summary: str = Field(
        ...,
        description="A concise summary of the root cause based on alert data and knowledge retrieval.",
    )
    resolution_steps: str = Field(
        ..., description="Actionable steps or commands suggested to resolve the issue."
    )
    knowledge_sources: List[str] = Field(
        default_factory=list,
        description="List of knowledge base documents or URLs used for grounding.",
    )


# --- 3. ADK Tools (RAG/Knowledge Base Placeholder) ---


# In a production environment, this tool would use VertexAIRagRetrieval to query your indexed corpus.
# This placeholder simulates that process by reading from a simple local JSON file.
def get_documentation(query: str, labels: Dict[str, str]) -> str:
    """
    Simulates retrieval of relevant documentation based on a query and alert labels.

    Args:
        query: A query generated by an agent (e.g., "how to fix error X").
        labels: Key labels from the alert (e.g., alertname, service).

    Returns:
        Relevant knowledge text, or a failure message.
    """
    logger.info(
        f"RAG Tool activated with query: '{query}' and alertname: {labels.get('alertname')}"
    )

    # Simulated local knowledge base lookup
    try:
        with open(DB_PATH, "r") as f:
            knowledge_data = json.load(f)

        alert_name = labels.get("alertname", "default")
        # Look up knowledge by alert name
        relevant_docs = knowledge_data.get(
            alert_name,
            knowledge_data.get("default", "No specific documentation found."),
        )

        return f"Retrieved Knowledge:\n{relevant_docs}"

    except FileNotFoundError:
        return "Knowledge base file not found. Analysis will rely only on alert data."
    except Exception as e:
        return f"Error retrieving knowledge: {e}"


# Define the custom tool using ADK's FunctionTool
DocumentationRetrievalTool = FunctionTool(
    name="DocumentationRetrievalTool",
    description="Tool for searching the internal knowledge base for documentation, runbooks, and resolution steps.",
    func=get_documentation,
    parameters=[
        {
            "name": "query",
            "type": "string",
            "description": "The specific question to ask the knowledge base (e.g., 'What are the runbook steps for high_cpu_alert?').",
        },
        {
            "name": "labels",
            "type": "object",
            "description": "The full labels dictionary from the alert payload for contextual search.",
        },
    ],
)

# Initialize a dummy knowledge file for testing
initial_knowledge = {
    "HighLatencyAlert": "Runbook: 1. Check database connections. 2. Restart cache service 'service-xyz'. 3. Scale up frontend pods. Known fix: 'service-xyz' frequently gets stuck.",
    "DiskUsageHigh": "Runbook: 1. Clear old log files in /var/log/app. 2. Check for unexpected large temp files in /tmp.",
    "default": "General troubleshooting guide: check network connectivity, review recent deploys, and ensure sufficient resources.",
}
with open(DB_PATH, "w") as f:
    json.dump(initial_knowledge, f, indent=2)

# --- 4. ADK Agent Definitions (Supervisor Architecture) ---

# 4.1 Specialized Agents
AlertTriageAgent = LlmAgent(
    model=MODEL_NAME,
    name="TriageAgent",
    description="Specializes in analyzing the raw Alertmanager payload (labels and annotations) to determine the severity, component, and the initial probable cause.",
    instruction="You are an expert Alert Triage specialist. Your task is to extract the core problem and affected component from the raw alert data.",
    # No tools needed, just raw data analysis
)

KnowledgeRetrievalAgent = LlmAgent(
    model=MODEL_NAME,
    name="RetrievalAgent",
    description="Specializes in formulating knowledge retrieval queries and using the DocumentationRetrievalTool.",
    instruction="Analyze the Triage Agent's output. Formulate a precise question for the DocumentationRetrievalTool using the alert name and component to find the relevant runbook or fix.",
    tools=[DocumentationRetrievalTool],
)

ReportAnalysisAgent = LlmAgent(
    model=MODEL_NAME,
    name="ReportAgent",
    description="Specializes in synthesizing information from the TriageAgent and RetrievalAgent into a final, structured analysis report.",
    instruction=(
        "You are the final analyst. Combine the initial alert analysis with the retrieved knowledge. "
        "Your final output MUST be a JSON object conforming strictly to the AnalysisReport Pydantic schema."
    ),
    # Define the output schema for structured generation
    response_mime_type="application/json",
    response_schema=AnalysisReport.model_json_schema(),
)

# 4.2 Supervisor Agent (OpsSage) and Workflow
# The OpsSage agent is a SequentialAgent to ensure the flow is deterministic: Triage -> RAG -> Report.
sage_flow = SequentialAgent(
    name="sage",  # Root agent name
    description="The main OpsSage orchestrator. It executes a deterministic flow to analyze an alert.",
    sub_agents=[
        AlertTriageAgent,
        KnowledgeRetrievalAgent,
        ReportAnalysisAgent,
    ],
    # The final output of the ReportAnalysisAgent is what the SequentialAgent will return
    final_agent_name="ReportAgent",
)

# --- 5. FastAPI Application Setup ---


# Define the lifespan function to manage the ADK Runner lifecycle
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initializes the ADK Runner when the app starts and shuts it down when the app stops."""
    global runner
    try:
        # Initialize the ADK runner with the root agent
        runner = Runner(agent=sage_flow)
        logger.info("ADK Runner initialized with OpsSage Supervisor Agent.")
        yield
    except Exception as e:
        logger.error(f"Failed to initialize ADK Runner: {e}")
        # Allow the application to start even if ADK initialization fails, but mark it
        raise e


# Create the FastAPI app instance
app = FastAPI(
    title="OpsSage Multi-Agent System API",
    description="Endpoint for receiving Alertmanager webhooks and triggering the OpsSage ADK workflow.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.post("/alert", response_model=AnalysisReport)
async def handle_alert(payload: AlertPayload) -> AnalysisReport:
    """
    Receives an Alertmanager webhook payload and triggers the OpsSage multi-agent workflow.
    """
    if not payload.alerts:
        raise HTTPException(
            status_code=400, detail="Payload must contain at least one alert."
        )

    # We process the first alert for simplicity in this example
    alert_info = payload.alerts[0]
    alert_name = alert_info.labels.get("alertname", "Unknown Alert")
    logger.info(f"Received alert: {alert_name} (Status: {alert_info.status})")

    # 1. Prepare the input for the ADK agent
    # The ADK state/context is a dictionary where we store input/output
    initial_state = {
        "alert_data": alert_info.model_dump(),
        "alert_payload_raw": json.dumps(alert_info.model_dump(), indent=2),
    }

    # 2. Run the ADK multi-agent flow
    try:
        # We start the agent run and pass the initial state
        final_event: Event = await runner.run_async(
            EventInput(
                author="AlertManager",
                actions=EventActions(message=f"New alert received: {alert_name}"),
                state=initial_state,
            )
        )

        # 3. Extract the structured report from the final agent's output
        if final_event.actions and final_event.actions.message:
            # The ReportAgent is configured to return a JSON string
            report_json_str = final_event.actions.message.strip()

            # The LLM output might have markdown formatting, strip it if necessary
            if report_json_str.startswith("```json") and report_json_str.endswith(
                "```"
            ):
                report_json_str = report_json_str[7:-3].strip()

            final_report = AnalysisReport.model_validate_json(report_json_str)

            # 4. Standard Interface Output: Return the structured report
            # This structured JSON is the 'standard interface' that can be consumed
            # and formatted by a Telegram/Slack/Email wrapper service.
            return final_report

        raise HTTPException(
            status_code=500, detail="Agent returned empty or unexpected response."
        )

    except Exception as e:
        logger.error(f"ADK Workflow Error: {e}", exc_info=True)
        # Raise a more descriptive error for the Alertmanager to potentially log
        raise HTTPException(
            status_code=500, detail=f"ADK processing failed: {type(e).__name__} - {e}"
        )


# --- 6. RAG Document Ingestion (Conceptual Tool Interface) ---

# This function is a conceptual wrapper for the RAG ingestion flow, which would
# typically involve uploading files to Google Cloud Storage (GCS) and initiating
# indexing via Vertex AI RAG Engine.


def ingest_documentation_file(file_path: str, document_type: str = "pdf"):
    """
    Conceptual function to push documentations into the knowledge base.

    In a real implementation, this would:
    1. Upload file to GCS.
    2. Call the Vertex AI RAG Engine API to index the document into the corpus.
    3. Update the agent's RetrievalAgent with the new RAG corpus ID if necessary.
    """
    print("=" * 50)
    print(f"RAG Ingestion Flow Triggered for: {file_path} ({document_type})")
    print("--- Conceptual Steps ---")
    print("1. File upload to Google Cloud Storage (GCS).")
    print(
        "2. Call Vertex AI RAG Engine API (or similar ADK RAG component) to index the document."
    )
    print(
        "3. Indexing supports formats like PDF, DOCX, Docs, and Images (with multimodal indexing)."
    )
    print("4. Upon completion, the knowledge is available to the RetrievalAgent.")
    print("=" * 50)
    # This is not a runnable ADK tool, but an instructional section
    # showing where the RAG pipeline interface would sit.


# Example usage of the conceptual ingestion interface:
# ingest_documentation_file("/path/to/my_runbook.pdf")
# ingest_documentation_file("/path/to/service_specs.docx")
