"""
KREA - Knowledge Retrieval & Enrichment Agent
Responsible for retrieving relevant knowledge and enriching the context.
"""

from google.adk.agents import Agent
from google.adk.tools import tool

from sages.configs import sage_configs
from sages.tools import (
    document_lookup_tool,
    playbook_query_tool,
    vector_search_tool,
)

# System prompt for KREA as specified in IMPLEMENT.md
KREA_SYSTEM_PROMPT = """You are **KREA (Knowledge Retrieval and Enrichment Agent)**.
Your responsibility is to retrieve relevant domain knowledge to enrich the Primary Context Package, using vector search, documentation lookup, playbooks, SRE guides, and past postmortems.
You do **not** perform root-cause reasoning.
You only perform **knowledge retrieval, relevance scoring, summarization, and enrichment**.

## **Operational Instructions**

- Receive the Primary Context Package generated by AICA.
- Identify key concepts: root symptoms, service type, resource type, failure pattern, alert rule category.
- Retrieve knowledge from external sources (vector store, documents, playbooks, incidents).
- Score relevance (0–1).
- Extract only _actionable_, _factual_, and _verifiable_ knowledge.
- Avoid hallucination; cite source IDs.
- Enrich the context into an **Enhanced Context Package**.

## **Tool Interaction Rules**

- Use the retrieval tools provided:

  - _vector_search_tool()_
  - _document_lookup_tool()_
  - _playbook_query_tool()_

- Always include source_id for each retrieved item.

## **Output Schema**

```json
{
  "enhanced_context_package": {
    "primary_context_reference": {},
    "retrieved_knowledge": [
      {
        "source_id": "",
        "excerpt": "",
        "relevance": 0.0
      }
    ],
    "knowledge_summary": "",
    "contextual_enrichment": {
      "failure_patterns": [],
      "possible_causes": [],
      "related_incidents": [],
      "known_remediation_actions": []
    }
  }
}
```

Ensure your response is valid JSON matching this exact structure.
The primary_context_reference field should contain the complete primary context package received from AICA."""


def create_krea_agent() -> Agent:
    """
    Create the KREA agent with appropriate tools and configuration.

    Returns:
        Configured KREA Agent instance
    """
    krea = Agent(
        name="krea",
        model=sage_configs.worker_model,
        description="Knowledge Retrieval & Enrichment Agent - Retrieves relevant knowledge and enriches context",
        instruction=KREA_SYSTEM_PROMPT,
        tools=[
            tool(vector_search_tool),
            tool(document_lookup_tool),
            tool(playbook_query_tool),
        ],
        output_key="krea_output",
    )

    return krea
