# In a production environment, this tool would use VertexAIRagRetrieval to query your indexed corpus.
# This placeholder simulates that process by reading from a simple local JSON file.
def get_documentation(query: str, labels: Dict[str, str]) -> str:
    """
    Simulates retrieval of relevant documentation based on a query and alert labels.

    Args:
        query: A query generated by an agent (e.g., "how to fix error X").
        labels: Key labels from the alert (e.g., alertname, service).

    Returns:
        Relevant knowledge text, or a failure message.
    """
    logger.info(
        f"RAG Tool activated with query: '{query}' and alertname: {labels.get('alertname')}"
    )

    # Simulated local knowledge base lookup
    try:
        with open(DB_PATH, "r") as f:
            knowledge_data = json.load(f)

        alert_name = labels.get("alertname", "default")
        # Look up knowledge by alert name
        relevant_docs = knowledge_data.get(
            alert_name,
            knowledge_data.get("default", "No specific documentation found."),
        )

        return f"Retrieved Knowledge:\n{relevant_docs}"

    except FileNotFoundError:
        return "Knowledge base file not found. Analysis will rely only on alert data."
    except Exception as e:
        return f"Error retrieving knowledge: {e}"


# Define the custom tool using ADK's FunctionTool
DocumentationRetrievalTool = FunctionTool(
    name="DocumentationRetrievalTool",
    description="Tool for searching the internal knowledge base for documentation, runbooks, and resolution steps.",
    func=get_documentation,
    parameters=[
        {
            "name": "query",
            "type": "string",
            "description": "The specific question to ask the knowledge base (e.g., 'What are the runbook steps for high_cpu_alert?').",
        },
        {
            "name": "labels",
            "type": "object",
            "description": "The full labels dictionary from the alert payload for contextual search.",
        },
    ],
)

# Initialize a dummy knowledge file for testing
initial_knowledge = {
    "HighLatencyAlert": "Runbook: 1. Check database connections. 2. Restart cache service 'service-xyz'. 3. Scale up frontend pods. Known fix: 'service-xyz' frequently gets stuck.",
    "DiskUsageHigh": "Runbook: 1. Clear old log files in /var/log/app. 2. Check for unexpected large temp files in /tmp.",
    "default": "General troubleshooting guide: check network connectivity, review recent deploys, and ensure sufficient resources.",
}
with open(DB_PATH, "w") as f:
    json.dump(initial_knowledge, f, indent=2)
